spring:
  datasource:
    url: jdbc:mysql://mysql_9oormthonuniv_be:3306/mysql9
    username: user9
    password: password9
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # JPA를 통해 Entity에 작성한대로 테이블 자동 생성 -> 배포 시 변경
    show-sql: true  # SQL 쿼리 로깅 활성화 -> 배포 시 변경
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

#  docker:
#    compose:
#      enabled: true
#      file: compose.yaml  # 경로 주의

server:
  port: 8080  # Spring Boot API 포트

jwt:
  secret: ${APP_JWT_SECRET}
  expiration: ${APP_JWT_EXPIRATION_MS} # 1시간

cloud:
  aws:
    s3:
      bucket: 9oormthon-univ-s3-bucket
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
